"""Gmail email sender module using SMTP with App Passwords."""
import os
import re
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication


def send_email(recipient, subject, body_html, reply_to=None, attachments=None):
    """
    Send email via Gmail SMTP using App Password.

    Args:
        recipient: Email address
        subject: Email subject
        body_html: HTML body content
        reply_to: Optional reply-to address
        attachments: Optional list of file paths to attach (e.g. CV PDFs)

    Returns:
        True if sent successfully, False otherwise
    """
    try:
        gmail_address = os.getenv("GMAIL_ADDRESS")
        gmail_app_password = os.getenv("GMAIL_APP_PASSWORD")

        if not gmail_address or not gmail_app_password:
            print("❌ Missing GMAIL_ADDRESS or GMAIL_APP_PASSWORD in .env.local")
            print("   See SETUP.md for how to generate an App Password")
            return False

        # 'mixed' so we can carry both the HTML body and file attachments.
        msg = MIMEMultipart('mixed')
        msg['Subject'] = subject
        msg['From'] = gmail_address
        msg['To'] = recipient
        if reply_to:
            msg['Reply-To'] = reply_to

        # Attach HTML body
        msg.attach(MIMEText(body_html, 'html'))

        # Attach files (PDFs, etc.). Prefix each file with its offer (company_role) so
        # multiple strong matches don't all arrive as "cv.pdf"/"grading.md". The folder is
        # "<date>_<company_role>"; move the date to the end so the company/role leads the
        # filename (e.g. rtl_group_..._2026-06-11__cv.pdf).
        for path in (attachments or []):
            try:
                folder = os.path.basename(os.path.dirname(path))
                base = os.path.basename(path)
                m = re.match(r"(\d{4}-\d{2}-\d{2})_(.+)", folder)
                prefix = f"{m.group(2)}_{m.group(1)}" if m else folder
                display = f"{prefix}__{base}" if prefix else base
                with open(path, "rb") as fh:
                    part = MIMEApplication(fh.read(), Name=display)
                part["Content-Disposition"] = f'attachment; filename="{display}"'
                msg.attach(part)
            except Exception as e:
                print(f"   ⚠️  Could not attach {path}: {e}")

        # Send via Gmail SMTP
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(gmail_address, gmail_app_password)
            server.sendmail(gmail_address, recipient, msg.as_string())

        print(f"✅ Email sent to {recipient}")
        return True

    except smtplib.SMTPAuthenticationError:
        print("❌ Gmail authentication failed - check GMAIL_ADDRESS and GMAIL_APP_PASSWORD")
        return False
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False


def send_daily_digest(recipient, matches_by_type, dry_run=False, attachments=None):
    """
    Send daily job matches digest.

    Args:
        recipient: Email address
        matches_by_type: Dict with 'strong', 'good', 'consider' keys containing job gradings
        dry_run: If True, don't actually send
        attachments: Optional list of file paths (e.g. tailored CV PDFs) to attach

    Returns:
        True if successful
    """
    strong = matches_by_type.get('strong', [])
    good = matches_by_type.get('good', [])
    consider = matches_by_type.get('consider', [])
    attachments = attachments or []

    cv_note = (f"📎 {len(attachments)} file(s) attached — per strong match: tailored CV "
               f"(PDF + editable .tex), grading.md, how_to_apply.md, and the cached offer."
               if attachments else
               "Run with --full-pipeline to auto-generate tailored CVs for these.")

    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto;">
        <h2>🔍 Daily Job Matches - {len(strong) + len(good) + len(consider)} Offers</h2>

        <h3>🔥 Strong Matches ({len(strong)})</h3>
        <p>{cv_note}</p>
        {"".join([f"<p>{job}</p>" for job in strong])}

        <h3>✅ Good Matches ({len(good)})</h3>
        <p>Consider these but didn't auto-generate CV.</p>
        {"".join([f"<p>{job}</p>" for job in good])}

        <h3>⚠️ Consider ({len(consider)})</h3>
        <p>Lower match but could be interesting.</p>
        {"".join([f"<p>{job}</p>" for job in consider])}

        <hr>
        <p style="font-size: 12px; color: #666;">
          Generated by automated CV pipeline at {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}
        </p>
      </body>
    </html>
    """

    if dry_run:
        print("\n=== DRY RUN EMAIL ===")
        print(f"To: {recipient}")
        print(f"Subject: Daily Job Matches - {len(strong)} Strong Offers")
        print(f"Attachments: {attachments}")
        print(html_body)
        print("=== END DRY RUN ===\n")
        return True

    return send_email(
        recipient,
        f"Daily Job Matches - {len(strong)} Strong Offers",
        html_body,
        attachments=attachments,
    )
